package com.haloalligners.repository

import com.haloalligners.model.DocumentVerificationAndSignatureEntity
import org.springframework.data.jpa.repository.JpaRepository
import org.springframework.stereotype.Repository

@Repository
interface DocumentVerificationAndSignatureRepository : JpaRepository<DocumentVerificationAndSignatureEntity, Long>